
language: python

matrix:
 fast_finish: true
 include:
  - python: "3.5"
    env: NETWORKX_VERSION=networkx==2.2
  - python: "3.6"
    env: NETWORKX_VERSION=networkx==2.2
  - python: "3.7"
    env: NETWORKX_VERSION=networkx==2.2
  - python: "3.8"
    env: NETWORKX_VERSION=networkx==2.2
  - python: "3.6"
    env: NETWORKX_VERSION=networkx==2.3
  - python: "3.7"
    env: NETWORKX_VERSION=networkx==2.3
  - python: "3.8"
    env: NETWORKX_VERSION=networkx==2.3
  - python: "3.6"
    env: NETWORKX_VERSION=networkx==2.4
  - python: "3.7"
    env: NETWORKX_VERSION=networkx==2.4
  - python: "3.8"
    env: NETWORKX_VERSION=networkx==2.4
  - python: "3.6"
    env: NETWORKX_VERSION=networkx==2.5
  - python: "3.7"
    env: NETWORKX_VERSION=networkx==2.5
  - python: "3.8"
    env: NETWORKX_VERSION=networkx==2.5

install:
 - pip install $NETWORKX_VERSION
 - python setup.py install
script:
 - xvfb-run --auto-servernum --server-args="-screen 0 1024x768x24" python ./networkx_viewer/tests.py
